[package]
name = "sqlx_test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-session = "0.6"
actix-web = "4"
anyhow = "1"
async-trait = "0.1"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.5", features = ["postgres", "runtime-actix-rustls"] }
